# Use the official Node.js 22 image as a base
FROM node:22

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your app will run on
EXPOSE 3012

# Set default environment variables
ENV PORT=3012
ENV PASSWORD=neopin123

# Start the application
CMD ["node", "server.js"]
