services:
  app:
    image: node:22
    ports:
      - "3012:3012"
    environment:
      - PORT=3012
      - PASSWORD=neopin123
    volumes:
      - ./:/home/docker/neopin
    working_dir: /home/docker/neopin
    command: sh -c "npm install && node server.js"
