services:
  app:
    image: node:22
    ports:
      - "3012:3012"
    environment:
      - PORT=3012
      - PASSWORD=neopin123
    volumes:
      - .:/app:rw
    working_dir: /app:rw
    command: sh -c "npm install && node server.js"